### ISSUE TITLE
Leaked Token

### ISSUE THREAD

**Issue by SourSpoon** [higuratujino/PUBG-Club#1]
https://github.com/higuratujino/PUBG-Club/blob/b64e8790d36c44fa34248cecd769761ee4a5273b/hellowWorldBot.py#L63

You leaked your token! This gives anyone full access to your bot.
https://discordapp.com/developers/applications/me

Please leverage a config file of some kind and add the config to a gitignore

**Comment by higuratujino** [comment]
thank you. You've been very helpful.
